### ISSUE TITLE
Can't set Content-Type 

### ISSUE THREAD

**Issue by spbrien** [kennethreitz/bucketstore#14]
I'm allowed to set custom metadata, but there's no way to set the actual Content-Type for S3. I'll try to submit a pull request with an update when I get a chance, as it should be pretty straightforward.

**Comment by mamcmanus** [comment]
@spbrien I am still unable to set the Content-Type: https://github.com/kennethreitz/bucketstore/issues/17

Have you resolved this?

**Comment by spbrien** [comment]
@mamcmanus I submitted a pull request and it was merged, but I'm not sure if it ever made it into a release... likely because I was working too fast and carelessly broke some tests :\  Installing from the master branch works, though -- that's how I'm using the library in my projects for the moment.

**Comment by mamcmanus** [comment]
Hey @spbrien -- thanks and no worries...I'm also installing from the master branch and that works great!
