### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by eligundry** [kennethreitz/bucketstore#7]
Have there been any plans for testing the library? Do you have a testing framework preference? If not, I'd love to take a stab at it using tox, pytest and [vcrpy](https://github.com/kevin1024/vcrpy), which mocks boto 3 really well.

**Comment by kennethreitz** [comment]
sure!

**Comment by kennethreitz** [comment]
i think standard unit tests are a good starting point — nothing fancy, like tox or vcrpy. testest is great though — let's do that.

**Comment by eligundry** [comment]
Sorry, I have been super busy over the past few months. I do have a tox setup going and I ditched vcrpy a while ago for [moto](https://github.com/spulec/moto) as no recording is needed. I'll try to have something for you by the end of the weekend.

**Comment by kennethreitz** [comment]
Sounds great!
